# Generated by Django 3.2.12 on 2023-04-01 06:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_code',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='course_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
